import fs from 'fs';
import path from 'path';

// id, title, diff, topic, sig, desc, [[[in1], out1], [[in2], out2]]
const raw = [
  ["add-two-numbers","Add Two Numbers","Medium","Linked List, Math","addTwoNumbers(l1: integer[], l2: integer[]) => integer[]","You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list (represented as an array here for simplicity).",[[[ [2,4,3],[5,6,4] ],[7,0,8]],[[ [0],[0] ],[0]]]],
  ["longest-substring-without-repeating-characters","Longest Substring Without Repeating Characters","Medium","Hash Table, String, Sliding Window","lengthOfLongestSubstring(s: string) => integer","Given a string s, find the length of the longest substring without repeating characters.",[[[ "abcabcbb" ],3],[[ "bbbbb" ],1]]],
  ["longest-palindromic-substring","Longest Palindromic Substring","Medium","String, Dynamic Programming","longestPalindrome(s: string) => string","Given a string s, return the longest palindromic substring in s.",[[[ "babad" ],"bab"],[[ "cbbd" ],"bb"]]],
  ["zigzag-conversion","Zigzag Conversion","Medium","String","convert(s: string, numRows: integer) => string","The string 'PAYPALISHIRING' is written in a zigzag pattern on a given number of rows. Write the code that will take a string and make this conversion given a number of rows.",[[[ "PAYPALISHIRING",3 ],"PAHNAPLSIIGYIR"],[[ "PAYPALISHIRING",4 ],"PINALSIGYAHRPI"]]],
  ["reverse-integer","Reverse Integer","Medium","Math","reverse(x: integer) => integer","Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range, then return 0.",[[[ 123 ],321],[[ -123 ],-321]]],
  ["string-to-integer-atoi","String to Integer (atoi)","Medium","String","myAtoi(s: string) => integer","Implement the myAtoi(string s) function, which converts a string to a 32-bit signed integer (similar to C/C++'s atoi function).",[[[ "42" ],42],[[ "   -42" ],-42]]],
  ["container-with-most-water","Container With Most Water","Medium","Array, Two Pointers, Greedy","maxArea(height: integer[]) => integer","You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]). Find two lines that together with the x-axis form a container, such that the container contains the most water.",[[[ [1,8,6,2,5,4,8,3,7] ],49],[[ [1,1] ],1]]],
  ["integer-to-roman","Integer to Roman","Medium","Hash Table, Math, String","intToRoman(num: integer) => string","Roman numerals are represented by seven different symbols. Given an integer, convert it to a roman numeral.",[[[ 3 ],"III"],[[ 58 ],"LVIII"],[[ 1994 ],"MCMXCIV"]]],
  ["3sum","3Sum","Medium","Array, Two Pointers, Sorting","threeSum(nums: integer[]) => integer[][]","Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.",[[[ [-1,0,1,2,-1,-4] ],[[-1,-1,2],[-1,0,1]]],[[ [0,1,1] ],[]]]],
  ["3sum-closest","3Sum Closest","Medium","Array, Two Pointers, Sorting","threeSumClosest(nums: integer[], target: integer) => integer","Given an integer array nums of length n and an integer target, find three integers in nums such that the sum is closest to target.",[[[ [-1,2,1,-4],1 ],2],[[ [0,0,0],1 ],0]]],
  ["letter-combinations-of-a-phone-number","Letter Combinations of a Phone Number","Medium","Hash Table, String, Backtracking","letterCombinations(digits: string) => string[]","Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.",[[[ "23" ],["ad","ae","af","bd","be","bf","cd","ce","cf"]],[[ "" ],[]]]],
  ["4sum","4Sum","Medium","Array, Two Pointers, Sorting","fourSum(nums: integer[], target: integer) => integer[][]","Given an array nums of n integers, return an array of all the unique quadruplets [nums[a], nums[b], nums[c], nums[d]] such that the sum is equal to target.",[[[ [1,0,-1,0,-2,2],0 ],[[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]],[[ [2,2,2,2,2],8 ],[[2,2,2,2]]]]],
  ["remove-nth-node-from-end-of-list","Remove Nth Node From End of List","Medium","Linked List, Two Pointers","removeNthFromEnd(head: integer[], n: integer) => integer[]","Given the head of a linked list (represented as array), remove the nth node from the end of the list and return its head.",[[[ [1,2,3,4,5],2 ],[1,2,3,5]],[[ [1],1 ],[]]]],
  ["generate-parentheses","Generate Parentheses","Medium","String, Dynamic Programming, Backtracking","generateParenthesis(n: integer) => string[]","Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.",[[[ 3 ],["((()))","(()())","(())()","()(())","()()()"]],[[ 1 ],["()"]]]],
  ["swap-nodes-in-pairs","Swap Nodes in Pairs","Medium","Linked List, Recursion","swapPairs(head: integer[]) => integer[]","Given a linked list (array), swap every two adjacent nodes and return its head.",[[[ [1,2,3,4] ],[2,1,4,3]],[[ [] ],[]]]],
  ["divide-two-integers","Divide Two Integers","Medium","Math, Bit Manipulation","divide(dividend: integer, divisor: integer) => integer","Given two integers dividend and divisor, divide two integers without using multiplication, division, and mod operator.",[[[ 10,3 ],3],[[ 7,-3 ],-2]]],
  ["next-permutation","Next Permutation","Medium","Array, Two Pointers","nextPermutation(nums: integer[]) => integer[]","A permutation of an array of integers is an arrangement of its members into a sequence or linear order. Find the next lexicographically greater permutation of its integer.",[[[ [1,2,3] ],[1,3,2]],[[ [3,2,1] ],[1,2,3]]]],
  ["search-in-rotated-sorted-array","Search in Rotated Sorted Array","Medium","Array, Binary Search","search(nums: integer[], target: integer) => integer","There is an integer array nums sorted in ascending order (with distinct values) which is possibly rotated. Given target, return the index if found, else -1.",[[[ [4,5,6,7,0,1,2],0 ],4],[[ [4,5,6,7,0,1,2],3 ],-1]]],
  ["find-first-and-last-position-of-element-in-sorted-array","Find First and Last Position of Element in Sorted Array","Medium","Array, Binary Search","searchRange(nums: integer[], target: integer) => integer[]","Given an array of integers nums sorted in non-decreasing order, find the starting and ending position of a given target value.",[[[ [5,7,7,8,8,10],8 ],[3,4]],[[ [5,7,7,8,8,10],6 ],[-1,-1]]]],
  ["valid-sudoku","Valid Sudoku","Medium","Array, Hash Table, Matrix","isValidSudoku(board: string[][]) => boolean","Determine if a 9 x 9 Sudoku board is valid. Only the filled cells need to be validated according to the Sudoku rules.",[[[ [["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]] ],true]]],
  ["count-and-say","Count and Say","Medium","String","countAndSay(n: integer) => string","The count-and-say sequence is a sequence of digit strings defined by the recursive formula. Given a positive integer n, return the nth term of the count-and-say sequence.",[[[ 1 ],"1"],[[ 4 ],"1211"]]],
  ["combination-sum","Combination Sum","Medium","Array, Backtracking","combinationSum(candidates: integer[], target: integer) => integer[][]","Given an array of distinct integers candidates and a target integer target, return a list of all unique combinations of candidates where the chosen numbers sum to target.",[[[ [2,3,6,7],7 ],[[2,2,3],[7]]],[[ [2,3,5],8 ],[[2,2,2,2],[2,3,3],[3,5]]]]],
  ["combination-sum-ii","Combination Sum II","Medium","Array, Backtracking","combinationSum2(candidates: integer[], target: integer) => integer[][]","Given a collection of candidate numbers (candidates) and a target number (target), find all unique combinations in candidates where the candidate numbers sum to target.",[[[ [10,1,2,7,6,1,5],8 ],[[1,1,6],[1,2,5],[1,7],[2,6]]],[[ [2,5,2,1,2],5 ],[[1,2,2],[5]]]]],
  ["multiply-strings","Multiply Strings","Medium","Math, String, Simulation","multiply(num1: string, num2: string) => string","Given two non-negative integers num1 and num2 represented as strings, return the product of num1 and num2, also represented as a string.",[[[ "2","3" ],"6"],[[ "123","456" ],"56088"]]],
  ["jump-game","Jump Game","Medium","Array, Dynamic Programming, Greedy","canJump(nums: integer[]) => boolean","You are given an integer array nums. You are initially positioned at the array's first index, and each element in the array represents your maximum jump length at that position. Return true if you can reach the last index, or false otherwise.",[[[ [2,3,1,1,4] ],true],[[ [3,2,1,0,4] ],false]]],
  ["permutations","Permutations","Medium","Array, Backtracking","permute(nums: integer[]) => integer[][]","Given an array nums of distinct integers, return all the possible permutations. You can return the answer in any order.",[[[ [1,2,3] ],[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]],[[ [0,1] ],[[0,1],[1,0]]]]],
  ["permutations-ii","Permutations II","Medium","Array, Backtracking","permuteUnique(nums: integer[]) => integer[][]","Given a collection of numbers, nums, that might contain duplicates, return all possible unique permutations in any order.",[[[ [1,1,2] ],[[1,1,2],[1,2,1],[2,1,1]]],[[ [1,2,3] ],[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]]]],
  ["rotate-image","Rotate Image","Medium","Array, Math, Matrix","rotate(matrix: integer[][]) => integer[][]","You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).",[[[ [[1,2,3],[4,5,6],[7,8,9]] ],[[7,4,1],[8,5,2],[9,6,3]]],[[ [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]] ],[[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]]]],
  ["group-anagrams","Group Anagrams","Medium","Array, Hash Table, String, Sorting","groupAnagrams(strs: string[]) => string[][]","Given an array of strings strs, group the anagrams together. You can return the answer in any order.",[[[ ["eat","tea","tan","ate","nat","bat"] ],[["bat"],["nat","tan"],["ate","eat","tea"]]],[[ [""] ],[[""]]]]],
  ["powx-n","Pow(x, n)","Medium","Math, Recursion","myPow(x: integer, n: integer) => integer","Implement pow(x, n), which calculates x raised to the power n (i.e., xn).",[[[ 2.0,10 ],1024.0],[[ 2.0,-2 ],0.25]]],
  ["maximum-subarray","Maximum Subarray","Medium","Array, Divide and Conquer, Dynamic Programming","maxSubArray(nums: integer[]) => integer","Given an integer array nums, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.",[[[ [-2,1,-3,4,-1,2,1,-5,4] ],6],[[ [1] ],1]]],
  ["spiral-matrix","Spiral Matrix","Medium","Array, Matrix, Simulation","spiralOrder(matrix: integer[][]) => integer[]","Given an m x n matrix, return all elements of the matrix in spiral order.",[[[ [[1,2,3],[4,5,6],[7,8,9]] ],[1,2,3,6,9,8,7,4,5]],[[ [[1,2,3,4],[5,6,7,8],[9,10,11,12]] ],[1,2,3,4,8,12,11,10,9,5,6,7]]]],
  ["jump-game-ii","Jump Game II","Medium","Array, Dynamic Programming, Greedy","jump(nums: integer[]) => integer","Given an array of non-negative integers nums, you are initially positioned at the first index of the array. Each element in the array represents your maximum jump length at that position. Your goal is to reach the last index in the minimum number of jumps.",[[[ [2,3,1,1,4] ],2],[[ [2,3,0,1,4] ],2]]],
  ["merge-intervals","Merge Intervals","Medium","Array, Sorting","merge(intervals: integer[][]) => integer[][]","Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.",[[[ [[1,3],[2,6],[8,10],[15,18]] ],[[1,6],[8,10],[15,18]]],[[ [[1,4],[4,5]] ],[[1,5]]]]],
  ["insert-interval","Insert Interval","Medium","Array","insert(intervals: integer[][], newInterval: integer[]) => integer[][]","You are given an array of non-overlapping intervals intervals where intervals[i] = [starti, endi] represent the start and the end of the ith interval and intervals is sorted in ascending order by starti. You are also given an interval newInterval = [start, end] that represents the start and end of another interval. Insert newInterval into intervals such that intervals is still sorted in ascending order by starti and intervals still does not have any overlapping intervals (merge overlapping intervals if necessary).",[[[ [[1,3],[6,9]],[2,5] ],[[1,5],[6,9]]],[[ [[1,2],[3,5],[6,7],[8,10],[12,16]],[4,8] ],[[1,2],[3,10],[12,16]]]]],
  ["spiral-matrix-ii","Spiral Matrix II","Medium","Array, Matrix, Simulation","generateMatrix(n: integer) => integer[][]","Given a positive integer n, generate an n x n matrix filled with elements from 1 to n2 in spiral order.",[[[ 3 ],[[1,2,3],[8,9,4],[7,6,5]]],[[ 1 ],[[1]]]]],
  ["rotate-list","Rotate List","Medium","Linked List, Two Pointers","rotateRight(head: integer[], k: integer) => integer[]","Given the head of a linked list (represented as array), rotate the list to the right by k places.",[[[ [1,2,3,4,5],2 ],[4,5,1,2,3]],[[ [0,1,2],4 ],[2,0,1]]]],
  ["unique-paths","Unique Paths","Medium","Math, Dynamic Programming, Combinatorics","uniquePaths(m: integer, n: integer) => integer","A robot is located at the top-left corner of a m x n grid. The robot can only move either down or right at any point in time. The robot is trying to reach the bottom-right corner of the grid. How many possible unique paths are there?",[[[ 3,7 ],28],[[ 3,2 ],3]]],
  ["unique-paths-ii","Unique Paths II","Medium","Array, Dynamic Programming, Matrix","uniquePathsWithObstacles(obstacleGrid: integer[][]) => integer","A robot is located at the top-left corner of a m x n grid. The robot can only move either down or right at any point in time. The robot is trying to reach the bottom-right corner of the grid. Now consider if some obstacles are added to the grids. How many unique paths would there be?",[[[ [[0,0,0],[0,1,0],[0,0,0]] ],2],[[ [[0,1],[0,0]] ],1]]],
  ["minimum-path-sum","Minimum Path Sum","Medium","Array, Dynamic Programming, Matrix","minPathSum(grid: integer[][]) => integer","Given a m x n grid filled with non-negative numbers, find a path from top left to bottom right, which minimizes the sum of all numbers along its path. Note: You can only move either down or right at any point in time.",[[[ [[1,3,1],[1,5,1],[4,2,1]] ],7],[[ [[1,2,3],[4,5,6]] ],12]]],
  ["set-matrix-zeroes","Set Matrix Zeroes","Medium","Array, Hash Table, Matrix","setZeroes(matrix: integer[][]) => integer[][]","Given an m x n integer matrix matrix, if an element is 0, set its entire row and column to 0's.",[[[ [[1,1,1],[1,0,1],[1,1,1]] ],[[1,0,1],[0,0,0],[1,0,1]]],[[ [[0,1,2,0],[3,4,5,2],[1,3,1,5]] ],[[0,0,0,0],[0,4,5,0],[0,3,1,0]]]]],
  ["search-a-2d-matrix","Search a 2D Matrix","Medium","Array, Binary Search, Matrix","searchMatrix(matrix: integer[][], target: integer) => boolean","Write an efficient algorithm that searches for a value in an m x n matrix. This matrix has the following properties: Integers in each row are sorted from left to right. The first integer of each row is greater than the last integer of the previous row.",[[[ [[1,3,5,7],[10,11,16,20],[23,30,34,60]],3 ],true],[[ [[1,3,5,7],[10,11,16,20],[23,30,34,60]],13 ],false]]],
  ["sort-colors","Sort Colors","Medium","Array, Two Pointers, Sorting","sortColors(nums: integer[]) => integer[]","Given an array nums with n objects colored red, white, or blue, sort them in-place so that objects of the same color are adjacent, with the colors in the order red, white, and blue. We will use the integers 0, 1, and 2 to represent the color red, white, and blue, respectively.",[[[ [2,0,2,1,1,0] ],[0,0,1,1,2,2]],[[ [2,0,1] ],[0,1,2]]]],
  ["combinations","Combinations","Medium","Backtracking","combine(n: integer, k: integer) => integer[][]","Given two integers n and k, return all possible combinations of k numbers out of the range [1, n]. You may return the answer in any order.",[[[ 4,2 ],[[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]]],[[ 1,1 ],[[1]]]]],
  ["subsets","Subsets","Medium","Array, Backtracking, Bit Manipulation","subsets(nums: integer[]) => integer[][]","Given an integer array nums of unique elements, return all possible subsets (the power set). The solution set must not contain duplicate subsets. Return the solution in any order.",[[[ [1,2,3] ],[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]],[[ [0] ],[[],[0]]]]],
  ["word-search","Word Search","Medium","Array, Backtracking, Matrix","exist(board: string[][], word: string) => boolean","Given an m x n grid of characters board and a string word, return true if word exists in the grid.",[[[ [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]],"ABCCED" ],true],[[ [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]],"SEE" ],true]]],
  ["remove-duplicates-from-sorted-array-ii","Remove Duplicates from Sorted Array II","Medium","Array, Two Pointers","removeDuplicates(nums: integer[]) => integer[]","Given an integer array nums sorted in non-decreasing order, remove some duplicates in-place such that each unique element appears at most twice. The relative order of the elements should be kept the same. Return the array.",[[[ [1,1,1,2,2,3] ],[1,1,2,2,3]],[[ [0,0,1,1,1,1,2,3,3] ],[0,0,1,1,2,3,3]]]],
  ["search-in-rotated-sorted-array-ii","Search in Rotated Sorted Array II","Medium","Array, Binary Search","search(nums: integer[], target: integer) => boolean","There is an integer array nums sorted in non-decreasing order (not necessarily with distinct values). Before being passed to your function, nums is rotated at an unknown pivot index k. Given target, return true if target is in nums, or false if it is not in nums.",[[[ [2,5,6,0,0,1,2],0 ],true],[[ [2,5,6,0,0,1,2],3 ],false]]],
  ["decode-ways","Decode Ways","Medium","String, Dynamic Programming","numDecodings(s: string) => integer","A message containing letters from A-Z can be encoded into numbers using the following mapping: 'A' -> 1, 'B' -> 2... 'Z' -> 26. Given a string s containing only digits, return the number of ways to decode it.",[[[ "12" ],2],[[ "226" ],3],[[ "0" ],0]]],
  ["reverse-linked-list-ii","Reverse Linked List II","Medium","Linked List","reverseBetween(head: integer[], left: integer, right: integer) => integer[]","Given the head of a singly linked list (represented as an array) and two integers left and right where left <= right, reverse the nodes of the list from position left to position right, and return the reversed list.",[[[ [1,2,3,4,5],2,4 ],[1,4,3,2,5]],[[ [5],1,1 ],[5]]]],

  ["median-of-two-sorted-arrays","Median of Two Sorted Arrays","Hard","Array, Binary Search, Divide and Conquer","findMedianSortedArrays(nums1: integer[], nums2: integer[]) => integer","Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.",[[[ [1,3],[2] ],2.0],[[ [1,2],[3,4] ],2.5]]],
  ["regular-expression-matching","Regular Expression Matching","Hard","String, Dynamic Programming","isMatch(s: string, p: string) => boolean","Given an input string s and a pattern p, implement regular expression matching with support for '.' and '*' where: '.' Matches any single character. '*' Matches zero or more of the preceding element.",[[[ "aa","a" ],false],[[ "aa","a*" ],true],[[ "ab",".*" ],true]]],
  ["merge-k-sorted-lists","Merge k Sorted Lists","Hard","Linked List, Divide and Conquer, Heap (Priority Queue), Merge Sort","mergeKLists(lists: integer[][]) => integer[]","You are given an array of k linked-lists lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it (represented as array).",[[[ [[1,4,5],[1,3,4],[2,6]] ],[1,1,2,3,4,4,5,6]],[[ [] ],[]]]],
  ["reverse-nodes-in-k-group","Reverse Nodes in k-Group","Hard","Linked List, Recursion","reverseKGroup(head: integer[], k: integer) => integer[]","Given a linked list (as array), reverse the nodes of a linked list k at a time and return its modified list.",[[[ [1,2,3,4,5],2 ],[2,1,4,3,5]],[[ [1,2,3,4,5],3 ],[3,2,1,4,5]]]],
  ["substring-with-concatenation-of-all-words","Substring with Concatenation of All Words","Hard","Hash Table, String, Sliding Window","findSubstring(s: string, words: string[]) => integer[]","You are given a string s and an array of strings words of the same length. Return all starting indices of substring(s) in s that is a concatenation of each word in words exactly once, in any order, and without any intervening characters.",[[[ "barfoothefoobarman",["foo","bar"] ],[0,9]],[[ "wordgoodgoodgoodbestword",["word","good","best","word"] ],[]]]],
  ["longest-valid-parentheses","Longest Valid Parentheses","Hard","String, Dynamic Programming, Stack","longestValidParentheses(s: string) => integer","Given a string containing just the characters '(' and ')', find the length of the longest valid (well-formed) parentheses substring.",[[[ "(()" ],2],[[ ")()())" ],4],[[ "" ],0]]],
  ["sudoku-solver","Sudoku Solver","Hard","Array, Backtracking, Matrix","solveSudoku(board: string[][]) => string[][]","Write a program to solve a Sudoku puzzle by filling the empty cells. A sudoku solution must satisfy all of the following rules: Each of the digits 1-9 must occur exactly once in each row, each column, and each of the 9 3x3 sub-boxes of the grid.",[[[ [["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]] ],[["5","3","4","6","7","8","9","1","2"],["6","7","2","1","9","5","3","4","8"],["1","9","8","3","4","2","5","6","7"],["8","5","9","7","6","1","4","2","3"],["4","2","6","8","5","3","7","9","1"],["7","1","3","9","2","4","8","5","6"],["9","6","1","5","3","7","2","8","4"],["2","8","7","4","1","9","6","3","5"],["3","4","5","2","8","6","1","7","9"]]]]],
  ["first-missing-positive","First Missing Positive","Hard","Array, Hash Table","firstMissingPositive(nums: integer[]) => integer","Given an unsorted integer array nums, return the smallest missing positive integer. You must implement an algorithm that runs in O(n) time and uses constant extra space.",[[[ [1,2,0] ],3],[[ [3,4,-1,1] ],2],[[ [7,8,9,11,12] ],1]]],
  ["trapping-rain-water","Trapping Rain Water","Hard","Array, Two Pointers, Dynamic Programming, Stack","trap(height: integer[]) => integer","Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.",[[[ [0,1,0,2,1,0,1,3,2,1,2,1] ],6],[[ [4,2,0,3,2,5] ],9]]],
  ["wildcard-matching","Wildcard Matching","Hard","String, Dynamic Programming, Greedy, Recursion","isMatch(s: string, p: string) => boolean","Given an input string (s) and a pattern (p), implement wildcard pattern matching with support for '?' and '*' where: '?' Matches any single character. '*' Matches any sequence of characters (including the empty sequence).",[[[ "aa","a" ],false],[[ "aa","*" ],true],[[ "cb","?a" ],false]]],
  ["n-queens","N-Queens","Hard","Array, Backtracking","solveNQueens(n: integer) => string[][]","The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other. Given an integer n, return all distinct solutions to the n-queens puzzle.",[[[ 4 ],[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]],[[ 1 ],[["Q"]]]]],
  ["n-queens-ii","N-Queens II","Hard","Backtracking","totalNQueens(n: integer) => integer","The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other. Given an integer n, return the number of distinct solutions to the n-queens puzzle.",[[[ 4 ],2],[[ 1 ],1]]],
  ["text-justification","Text Justification","Hard","Array, String, Simulation","fullJustify(words: string[], maxWidth: integer) => string[]","Given an array of strings words and a width maxWidth, format the text such that each line has exactly maxWidth characters and is fully (left and right) justified.",[[[ ["This", "is", "an", "example", "of", "text", "justification."],16 ],["This    is    an","example  of text","justification.  "]]]],
  ["valid-number","Valid Number","Hard","String","isNumber(s: string) => boolean","A valid number can be split up into these components (in order): A decimal number or an integer, (Optional) An 'e' or 'E', followed by an integer.",[[[ "0" ],true],[[ "e" ],false],[[ "." ],false]]],
  ["edit-distance","Edit Distance","Hard","String, Dynamic Programming","minDistance(word1: string, word2: string) => integer","Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.",[[[ "horse","ros" ],3],[[ "intention","execution" ],5]]],
  ["scramble-string","Scramble String","Hard","String, Dynamic Programming","isScramble(s1: string, s2: string) => boolean","We can scramble a string s to get a string t using the following algorithm: If the length of the string is 1, stop. If the length of the string is > 1, do the following: Split the string into two non-empty substrings at a random index. Decide to swap the two substrings or to keep them in the same order. Apply the steps recursively.",[[[ "great","rgeat" ],true],[[ "abcde","caebd" ],false]]],
  ["maximal-rectangle","Maximal Rectangle","Hard","Array, Dynamic Programming, Stack, Matrix","maximalRectangle(matrix: string[][]) => integer","Given a rows x cols binary matrix filled with 0's and 1's, find the largest rectangle containing only 1's and return its area.",[[[ [["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]] ],6],[[ [] ],0]]],
  ["largest-rectangle-in-histogram","Largest Rectangle in Histogram","Hard","Array, Stack, Monotonic Stack","largestRectangleArea(heights: integer[]) => integer","Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.",[[[ [2,1,5,6,2,3] ],10],[[ [2,4] ],4]]],
  ["interleaving-string","Interleaving String","Hard","String, Dynamic Programming","isInterleave(s1: string, s2: string, s3: string) => boolean","Given strings s1, s2, and s3, find whether s3 is formed by an interleaving of s1 and s2.",[[[ "aabcc","dbbca","aadbbcbcac" ],true],[[ "aabcc","dbbca","aadbbbaccc" ],false]]],
  ["recover-binary-search-tree","Recover Binary Search Tree","Hard","Tree, Depth-First Search, Binary Search Tree, Binary Tree","recoverTree(root: integer[]) => integer[]","You are given the root of a binary search tree (BST) represented as an array where exactly two nodes of the tree were swapped by mistake. Recover the tree without changing its structure.",[[[ [1,3,null,null,2] ],[3,1,null,null,2]],[[ [3,1,4,null,null,2] ],[2,1,4,null,null,3]]]],
  ["distinct-subsequences","Distinct Subsequences","Hard","String, Dynamic Programming","numDistinct(s: string, t: string) => integer","Given two strings s and t, return the number of distinct subsequences of s which equals t.",[[[ "rabbbit","rabbit" ],3],[[ "babgbag","bag" ],5]]],
  ["word-ladder-ii","Word Ladder II","Hard","Hash Table, String, Backtracking, Breadth-First Search","findLadders(beginWord: string, endWord: string, wordList: string[]) => string[][]","A transformation sequence from word beginWord to word endWord using a dictionary wordList is a sequence of words beginWord -> s1 -> s2 -> ... -> sk.",[[[ "hit","cog",["hot","dot","dog","lot","log","cog"] ],[["hit","hot","dot","dog","cog"],["hit","hot","lot","log","cog"]]]]],
  ["best-time-to-buy-and-sell-stock-iii","Best Time to Buy and Sell Stock III","Hard","Array, Dynamic Programming","maxProfit(prices: integer[]) => integer","You are given an array prices where prices[i] is the price of a given stock on the ith day. Find the maximum profit you can achieve. You may complete at most two transactions.",[[[ [3,3,5,0,0,3,1,4] ],6],[[ [1,2,3,4,5] ],4]]],
  ["binary-tree-maximum-path-sum","Binary Tree Maximum Path Sum","Hard","Dynamic Programming, Tree, Depth-First Search, Binary Tree","maxPathSum(root: integer[]) => integer","A path in a binary tree is a sequence of nodes where each pair of adjacent nodes in the sequence has an edge connecting them. For this problem, a path is considered any sequence of nodes from some starting node to any node in the tree along the parent-child connections. Return the maximum path sum of any non-empty path.",[[[ [1,2,3] ],6],[[ [-10,9,20,null,null,15,7] ],42]]],
  ["word-break-ii","Word Break II","Hard","Hash Table, String, Dynamic Programming, Backtracking, Trie, Memoization","wordBreak(s: string, wordDict: string[]) => string[]","Given a string s and a dictionary of strings wordDict, add spaces in s to construct a sentence where each word is a valid dictionary word. Return all such possible sentences in any order.",[[[ "catsanddog",["cat","cats","and","sand","dog"] ],["cats and dog","cat sand dog"]]]],
  ["candy","Candy","Hard","Array, Greedy","candy(ratings: integer[]) => integer","There are n children standing in a line. Each child is assigned a rating value given in the integer array ratings. You are giving candies to these children subjected to the following requirements: Each child must have at least one candy. Children with a higher rating get more candies than their neighbors.",[[[ [1,0,2] ],5],[[ [1,2,2] ],4]]],
  ["max-points-on-a-line","Max Points on a Line","Hard","Array, Hash Table, Math, Geometry","maxPoints(points: integer[][]) => integer","Given an array of points where points[i] = [xi, yi] represents a point on the X-Y plane, return the maximum number of points that lie on the same straight line.",[[[ [[1,1],[2,2],[3,3]] ],3],[[ [[1,1],[3,2],[5,3],[4,1],[2,3],[1,4]] ],4]]],
  ["find-minimum-in-rotated-sorted-array-ii","Find Minimum in Rotated Sorted Array II","Hard","Array, Binary Search","findMin(nums: integer[]) => integer","Suppose an array of length n sorted in ascending order is rotated between 1 and n times. Notice that it may contain duplicates. Given the sorted rotated array nums that may contain duplicates, return the minimum element of this array.",[[[ [1,3,5] ],1],[[ [2,2,2,0,1] ],0]]],
  ["maximum-gap","Maximum Gap","Hard","Array, Sorting, Bucket Sort, Radix Sort","maximumGap(nums: integer[]) => integer","Given an integer array nums, return the maximum difference between two successive elements in its sorted form. If the array contains less than two elements, return 0.",[[[ [3,6,9,1] ],3],[[ [10] ],0]]],
  ["dungeon-game","Dungeon Game","Hard","Array, Dynamic Programming, Matrix","calculateMinimumHP(dungeon: integer[][]) => integer","The demons had captured the princess and imprisoned her in the bottom-right corner of a dungeon. The dungeon consists of m x n rooms laid out in a 2D grid. Our valiant knight was initially positioned in the top-left room and must fight his way through dungeon to rescue the princess. Write a function to determine the knight's minimum initial health so that he can rescue the princess.",[[[ [[-2,-3,3],[-5,-10,1],[10,30,-5]] ],7],[[ [[0]] ],1]]],
  ["best-time-to-buy-and-sell-stock-iv","Best Time to Buy and Sell Stock IV","Hard","Array, Dynamic Programming","maxProfit(k: integer, prices: integer[]) => integer","You are given an integer array prices where prices[i] is the price of a given stock on the ith day, and an integer k. Find the maximum profit you can achieve. You may complete at most k transactions.",[[[ 2,[2,4,1] ],2],[[ 2,[3,2,6,5,0,3] ],7]]],
  ["word-search-ii","Word Search II","Hard","Array, String, Backtracking, Trie, Matrix","findWords(board: string[][], words: string[]) => string[]","Given an m x n board of characters and a list of strings words, return all words on the board.",[[[ [["o","a","a","n"],["e","t","a","e"],["i","h","k","r"],["i","f","l","v"]],["oath","pea","eat","rain"] ],["eat","oath"]]]],
  ["shortest-palindrome","Shortest Palindrome","Hard","String, Rolling Hash, String Matching, KMP","shortestPalindrome(s: string) => string","You are given a string s. You can convert s to a palindrome by adding characters in front of it. Return the shortest palindrome you can find by performing this transformation.",[[[ "aacecaaa" ],"aaacecaaa"],[[ "abcd" ],"dcbabcd"]]],
  ["the-skyline-problem","The Skyline Problem","Hard","Array, Divide and Conquer, Binary Indexed Tree, Segment Tree, Line Sweep, Heap (Priority Queue), Ordered Set","getSkyline(buildings: integer[][]) => integer[][]","A city's skyline is the outer contour of the silhouette formed by all the buildings in that city when viewed from a distance. Given the locations and heights of all the buildings, return the skyline formed by these buildings collectively.",[[[ [[2,9,10],[3,7,15],[5,12,12],[15,20,10],[19,24,8]] ],[[2,10],[3,15],[7,12],[12,0],[15,10],[20,8],[24,0]]]]],
  ["sliding-window-maximum","Sliding Window Maximum","Hard","Array, Queue, Sliding Window, Heap (Priority Queue), Monotonic Queue","maxSlidingWindow(nums: integer[], k: integer) => integer[]","You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Each time the sliding window moves right by one position. Return the max sliding window.",[[[ [1,3,-1,-3,5,3,6,7],3 ],[3,3,5,5,6,7]],[[ [1],1 ],[1]]]],
  ["basic-calculator","Basic Calculator","Hard","Math, String, Stack, Recursion","calculate(s: string) => integer","Given a string s representing a valid expression, implement a basic calculator to evaluate it, and return the result of the evaluation.",[[[ "1 + 1" ],2],[[ " 2-1 + 2 " ],3],[[ "(1+(4+5+2)-3)+(6+8)" ],23]]],
  ["number-of-digit-one","Number of Digit One","Hard","Math, Dynamic Programming","countDigitOne(n: integer) => integer","Given an integer n, count the total number of digit 1 appearing in all non-negative integers less than or equal to n.",[[[ 13 ],6],[[ 0 ],0]]],
  ["count-of-smaller-numbers-after-self","Count of Smaller Numbers After Self","Hard","Array, Binary Search, Divide and Conquer, Binary Indexed Tree, Segment Tree, Merge Sort, Ordered Set","countSmaller(nums: integer[]) => integer[]","Given an integer array nums, return an integer array counts where counts[i] is the number of smaller elements to the right of nums[i].",[[[ [5,2,6,1] ],[2,1,1,0]],[[ [-1] ],[0]]]],
  ["remove-invalid-parentheses","Remove Invalid Parentheses","Hard","String, Backtracking, Breadth-First Search","removeInvalidParentheses(s: string) => string[]","Given a string s that contains parentheses and letters, remove the minimum number of invalid parentheses to make the input string valid. Return all the possible results. You may return the answer in any order.",[[[ "()())()" ],["(())()","()()()"]],[[ "(a)())()" ],["(a())()","(a)()()"]],[[ ")(" ],[""]]]],
  ["burst-balloons","Burst Balloons","Hard","Array, Dynamic Programming","maxCoins(nums: integer[]) => integer","You are given n balloons, indexed from 0 to n - 1. Each balloon is painted with a number on it represented by an array nums. You are asked to burst all the balloons. Return the maximum coins you can collect by bursting the balloons wisely.",[[[ [3,1,5,8] ],167],[[ [1,5] ],10]]],
  ["longest-increasing-path-in-a-matrix","Longest Increasing Path in a Matrix","Hard","Array, Dynamic Programming, Depth-First Search, Breadth-First Search, Graph, Topological Sort, Memoization, Matrix","longestIncreasingPath(matrix: integer[][]) => integer","Given an m x n integers matrix, return the length of the longest increasing path in matrix.",[[[ [[9,9,4],[6,6,8],[2,1,1]] ],4],[[ [[3,4,5],[3,2,6],[2,2,1]] ],4]]],
  ["palindrome-pairs","Palindrome Pairs","Hard","Array, Hash Table, String, Trie","palindromePairs(words: string[]) => integer[][]","Given a list of unique words, return all the pairs of the distinct indices (i, j) in the given list, so that the concatenation of the two words words[i] + words[j] is a palindrome.",[[[ ["abcd","dcba","lls","s","sssll"] ],[[0,1],[1,0],[3,2],[2,4]]],[[ ["bat","tab","cat"] ],[[0,1],[1,0]]]]],
  ["russian-doll-envelopes","Russian Doll Envelopes","Hard","Array, Binary Search, Dynamic Programming, Sorting","maxEnvelopes(envelopes: integer[][]) => integer","You are given a 2D array of integers envelopes where envelopes[i] = [wi, hi] represents the width and the height of an envelope. One envelope can fit into another if and only if both the width and height of one envelope are strictly smaller than the other envelope's width and height. Return the maximum number of envelopes you can Russian doll (i.e., put one inside other).",[[[ [[5,4],[6,4],[6,7],[2,3]] ],3],[[ [[1,1],[1,1],[1,1]] ],1]]],
  ["max-sum-of-rectangle-no-larger-than-k","Max Sum of Rectangle No Larger Than K","Hard","Array, Binary Search, Dynamic Programming, Matrix, Ordered Set","maxSumSubmatrix(matrix: integer[][], k: integer) => integer","Given an m x n matrix matrix and an integer k, return the max sum of a rectangle in the matrix such that its sum is no larger than k.",[[[ [[1,0,1],[0,-2,3]],2 ],2],[[ [[2,2,-1]],3 ],3]]],
  ["frog-jump","Frog Jump","Hard","Array, Dynamic Programming","canCross(stones: integer[]) => boolean","A frog is crossing a river. The river is divided into some number of units, and at each unit, there may or may not exist a stone. The frog can jump on a stone, but it must not jump into the water. Given a list of stones' positions (in units) in sorted strictly increasing order, determine if the frog can cross the river by landing on the last stone.",[[[ [0,1,3,5,6,8,12,17] ],true],[[ [0,1,2,3,4,8,9,11] ],false]]],
  ["split-array-largest-sum","Split Array Largest Sum","Hard","Array, Binary Search, Dynamic Programming, Greedy","splitArray(nums: integer[], k: integer) => integer","Given an array nums which consists of non-negative integers and an integer m, you can split the array into m non-empty continuous subarrays. Write an algorithm to minimize the largest sum among these m subarrays.",[[[ [7,2,5,10,8],2 ],18],[[ [1,2,3,4,5],2 ],9]]],
  ["strong-password-checker","Strong Password Checker","Hard","String, Greedy, Heap (Priority Queue)","strongPasswordChecker(password: string) => integer","A password is considered strong if it has at least 6 characters, at most 20 characters, contains at least one lowercase letter, at least one uppercase letter, and at least one digit, and does not contain three repeating characters in a row. Return the minimum number of steps to make password strong.",[[[ "a" ],5],[[ "aA1" ],3],[[ "1337C0d3" ],0]]],
  ["sliding-window-median","Sliding Window Median","Hard","Array, Hash Table, Sliding Window, Heap (Priority Queue)","medianSlidingWindow(nums: integer[], k: integer) => integer[]","The median is the middle value in an ordered integer list. If the size of the list is even, there is no middle value. So the median is the mean of the two middle values. You are given an integer array nums and an integer k. There is a sliding window of size k which is moving from the very left of the array to the very right. Return the median array for each window in the original array.",[[[ [1,3,-1,-3,5,3,6,7],3 ],[1.0,-1.0,-1.0,3.0,5.0,6.0]]]],
  ["concatenated-words","Concatenated Words","Hard","Array, String, Dynamic Programming, Depth-First Search, Trie","findAllConcatenatedWordsInADict(words: string[]) => string[]","Given an array of strings words (without duplicates), return all the concatenated words in the given list of words. A concatenated word is defined as a string that is comprised entirely of at least two shorter words in the given array.",[[[ ["cat","cats","catsdogcats","dog","dogcatsdog","hippopotamuses","rat","ratcatdogcat"] ],["catsdogcats","dogcatsdog","ratcatdogcat"]],[[ ["cat","dog","catdog"] ],["catdog"]]]],
  ["minimum-window-substring","Minimum Window Substring","Hard","Hash Table, String, Sliding Window","minWindow(s: string, t: string) => string","Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window. If there is no such substring, return the empty string \"\".",[[[ "ADOBECODEBANC","ABC" ],"BANC"],[[ "a","a" ],"a"],[[ "a","aa" ],""]]]
];

function parseSig(sig) {
  const parts = sig.split('=>');
  const returns = parts[1].trim();
  const left = parts[0].trim();
  const name = left.substring(0, left.indexOf('('));
  const paramsStr = left.substring(left.indexOf('(')+1, left.length-1);
  const params = paramsStr.split(',').map(s => {
    const [pn, pt] = s.split(':');
    return { name: pn.trim(), type: pt.trim() };
  });
  return { name, params, returns };
}

function generateStarterCode(sigObj) {
  const paramNames = sigObj.params.map(p => p.name).join(', ');
  let cppParams = sigObj.params.map(p => {
    let t = "int";
    if (p.type === 'integer[]') t = "vector<int>&";
    if (p.type === 'string') t = "string";
    if (p.type === 'string[]') t = "vector<string>&";
    if (p.type === 'integer[][]') t = "vector<vector<int>>&";
    if (p.type === 'string[][]') t = "vector<vector<string>>&";
    return `${t} ${p.name}`;
  }).join(', ');
  let cppRet = "int";
  if (sigObj.returns === 'boolean') cppRet = "bool";
  if (sigObj.returns === 'integer[]') cppRet = "vector<int>";
  if (sigObj.returns === 'string') cppRet = "string";
  if (sigObj.returns === 'string[]') cppRet = "vector<string>";
  if (sigObj.returns === 'integer[][]') cppRet = "vector<vector<int>>";
  if (sigObj.returns === 'string[][]') cppRet = "vector<vector<string>>";
  
  return {
    javascript: `function ${sigObj.name}(${paramNames}) {\n  \n}`,
    python: `def ${sigObj.name}(${paramNames}):\n    pass`,
    cpp: `class Solution {\npublic:\n    ${cppRet} ${sigObj.name}(${cppParams}) {\n        \n    }\n};`,
  };
}

const finalProblems = raw.map(d => {
  const sigObj = parseSig(d[4]);
  return {
    id: d[0],
    title: d[1],
    difficulty: d[2],
    topic: d[3],
    signature: sigObj,
    description: d[5],
    examples: d[6].map((t, i) => ({
      input: sigObj.params.map((p, pi) => `${p.name} = ${JSON.stringify(t[0][pi])}`).join(', '),
      output: JSON.stringify(t[1])
    })),
    constraints: ["Check problem description for constraints."],
    starterCode: generateStarterCode(sigObj),
    testCases: d[6].map(t => ({ input: t[0], expected: t[1] }))
  };
});

const fileOutput = `// Auto-generated 100 Medium & Hard Leetcode questions
import { CodingProblem } from './types';

export const codingProblems: CodingProblem[] = ${JSON.stringify(finalProblems, null, 2)};
`;

fs.writeFileSync(path.join(process.cwd(), 'src/data/codingProblems.ts'), fileOutput);
console.log('Successfully generated exactly ' + finalProblems.length + ' problems!');
