// Browser smoke test. Start the app on ALVIO_URL and its production preview on ALVIO_PREVIEW_URL.
// Install Playwright separately or provide PLAYWRIGHT_PACKAGE. Uses isolated, intercepted auth responses.
const appUrl = process.env.ALVIO_URL || 'http://127.0.0.1:3001';
const previewUrl = process.env.ALVIO_PREVIEW_URL || 'http://127.0.0.1:5174';
const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE || 'playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(`${appUrl}/`);await page.waitForSelector('.lp-hero');const problemCount = await page.request.get(`${appUrl}/api/problems`).then(r=>r.json()).then(rows=>rows.length);await page.waitForFunction(count=>document.querySelector('.lp-metrics strong')?.textContent===count.toLocaleString(),problemCount);
const hrefs=await page.locator('a').evaluateAll(es=>es.map(e=>e.getAttribute('href')));const routes=[...fs.readFileSync('src/App.tsx','utf8').matchAll(/path="([^"]+)"/g)].map(m=>m[1]);
for(const href of hrefs){assert(href&&href!=='#','No dead link');if(href.startsWith('#'))assert.equal(await page.locator(href).count(),1,`Anchor ${href}`);else assert(routes.includes(href.split('?')[0]),`Registered destination ${href}`);}
for(const a of await page.locator('.lp-desktop-nav a').all()){const hash=await a.getAttribute('href');await a.click();assert.equal(new URL(page.url()).hash,hash);assert((await page.locator(hash).boundingBox()).y>=60,`Anchor clears sticky header ${hash}`);}
for(const summary of await page.locator('.lp-faq summary').all()){await summary.focus();await page.keyboard.press('Enter');assert.equal(await summary.evaluate(e=>e.parentElement.open),true);await page.keyboard.press('Enter');}
await page.getByRole('button',{name:'Search Alvio',exact:true}).click();await page.getByRole('textbox',{name:'Search learning tools'}).fill('visual');assert.equal(await page.locator('.lp-search-links a').count(),1);await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').evaluate(e=>e.open),false);
for(const label of ['Privacy','Terms','Cookies','Contact']){await page.getByRole('button',{name:label,exact:true}).click();assert.equal(await page.locator('dialog').evaluate(e=>e.open),true);await page.keyboard.press('Escape');}
await page.getByRole('button',{name:'Next traversal step',exact:true}).click();await page.locator('.lp-preview-controls>span').getByText('2 / 7',{exact:true}).waitFor();await page.getByRole('button',{name:'Reset traversal',exact:true}).click();await page.locator('.lp-preview-controls>span').getByText('1 / 7',{exact:true}).waitFor();
for(let i=0;i<7;i++)await page.getByRole('button',{name:'Next sorting step',exact:true}).click();assert.equal(await page.locator('.lp-sort-status').innerText(),'Sorted');await page.getByRole('button',{name:'Try again',exact:true}).click();assert.equal(await page.locator('.lp-sort-status').innerText(),'Swap 0 of 7');
assert.deepEqual(await page.locator('[id]').evaluateAll(es=>{const ids=es.map(e=>e.id);return ids.filter((id,i)=>ids.indexOf(id)!==i)}),[],'No duplicate IDs');
await page.locator('.lp-final').scrollIntoViewIfNeeded();await page.waitForFunction(()=>Array.from(document.querySelectorAll('main img')).every(i=>i.complete&&i.naturalWidth>0));await page.locator('.lp-final').screenshot({path:'data/landing-final-cta.png'});
await page.goto(`${appUrl}/`);await page.waitForTimeout(350);await page.screenshot({path:'data/landing-final-desktop.png'});
for(const width of [768,390,360]){await page.setViewportSize({width,height:844});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`No horizontal overflow ${width}`);await page.getByRole('button',{name:'Open menu',exact:true}).click();await page.locator('.lp-mobile-nav').getByRole('link',{name:'Practice',exact:true}).click();assert.equal(await page.locator('.lp-mobile-nav').count(),0);await page.getByRole('button',{name:'Open menu',exact:true}).click();await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Open menu',exact:true}).evaluate(e=>e===document.activeElement),true);if(width===390){await page.goto(`${appUrl}/`);await page.waitForTimeout(350);await page.screenshot({path:'data/landing-final-mobile.png'});}}
// Exercise the real auth UI with an isolated browser and intercepted API responses, never create real accounts.
await page.setViewportSize({width:1200,height:900});
for(const mode of ['login','signup']){await page.goto(`${appUrl}/auth?mode=${mode}&next=%2Fdashboard`);await page.getByRole('heading',{name:mode==='login'?'Welcome back':'Create an account',exact:true}).waitFor();
 await page.route(`**/api/auth/${mode}`,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({user:{id:`landing-smoke-${mode}`,name:'Preview Student',email:'preview@example.test'},token:'isolated-preview-token'})}));
 if(mode==='signup')await page.getByLabel('Full Name',{exact:true}).fill('Preview Student');await page.getByLabel('Email Address',{exact:true}).fill('preview@example.test');await page.getByLabel('Password',{exact:true}).fill('test-only-password');await page.getByRole('button',{name:mode==='login'?'Sign in':'Create an account',exact:true}).click();await page.waitForURL('**/dashboard');await page.getByRole('heading',{name:/Good .*Preview/}).waitFor();assert.equal(await page.locator('.ad-metric').first().innerText().then(t=>t.includes('0 / 8')),true);await page.unroute(`**/api/auth/${mode}`);
}
assert.deepEqual(errors,[]);console.log('PASS: all link destinations, navbar anchors, all 8 keyboard FAQs, search, four footer dialogs, traversal controls, unique IDs, images, mobile menu and overflow at 768/390/360, login/signup modes and successful redirects with isolated mocked authentication.');
const prod=await browser.newPage({viewport:{width:1440,height:1000}});await prod.goto(`${previewUrl}/`);await prod.waitForSelector('.lp-hero');assert.equal(await prod.locator('.lp-testimonials').count(),0,'No demo testimonials in production');console.log('PASS: production hides development testimonials.');console.log('Initial production JS',await prod.evaluate(()=>performance.getEntriesByType('resource').filter(r=>r.name.endsWith('.js')).map(r=>({name:r.name.split('/').pop(),bytes:r.encodedBodySize}))));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
